### ISSUE TITLE
4clojure-check-answers gives: Symbol’s function definition is void: string-to-int

### ISSUE THREAD

**Issue by Macavirus** [emacsorphanage/4clojure#12]
Running Spacemacs and Cider, after completing a 4clojure question, the answer cannot be submitted.

Messages buffer shows:
```
[nREPL] Establishing direct connection to localhost:42341 ...
[nREPL] Direct connection to localhost:42341 established
helm-M-x: Symbol’s function definition is void: string-to-int [2 times]
```

**Comment by abend** [comment]
Hi.  This should be fixed in d5db917ecba83bdd21748fd8e452662e9fbf664a.  Let me know if you still have problems with the current version.
